### ISSUE TITLE
Version always shows as 0.2.0Beta, even though I manually installed v0.2.3 Beta

### ISSUE THREAD

**Issue by debsahu** [markwal/OctoPrint-PolarCloud#17]
Octoprint thinks there is a update even though v0.2.3 Beta is installed. The version reflected in Octoprint is v0.2.0 Beta.

**Comment by markwal** [comment]
Oops.  We've been forgetting to update the version number in setup.py, so it hasn't been matching the package archives.  :-(  0.2.5 Beta should be correct though.
