### ISSUE TITLE
Coming soon: gcodeFile

### ISSUE THREAD

**Issue by dnewman-polar3d** [markwal/OctoPrint-PolarCloud#21]
Shortly, a `print` command may have

    "gcodeFile": "URL to gcode file"

in place of

    "stlFile": "URL to STL file",
    "configFIle": "URL to slicing config file"

For such a `print` command, this would be a print job in which to simply print the supplied gcode.  These will come about as we're adding to the Polar Cloud the ability to simply upload gcode to create a queued print job.  Useful for folks who want to use their own slicer.

**Comment by vmorrisPolar** [comment]
Implemented in 2017, closing ticket.
