### ISSUE TITLE
Bed temp -1 reports as a bed present and with temp -1C

### ISSUE THREAD

**Issue by dnewman-polar3d** [markwal/OctoPrint-PolarCloud#29]
The plugin is seeing a bed temp of -1 and not recognizing that as "no bed" and then reporting that temp (-1C) to the cloud.

    Recv: ok T:209.48 /210 B:-1 /0 @:1 B@:0

The OctoPrint UI itself seems to recognize that this means that no bed is attached as it shows only a temp for "Tool" and no other temps.  (The printer is a Printerbot Simple Pro with a non-heated bed and the g2 electronics running tinyg.)

**Comment by dnewman-polar3d** [comment]
Fixed in branch issue-29.  See pull request #30

**Comment by markwal** [comment]
PR merged
