### ISSUE TITLE
Camera view issues

### ISSUE THREAD

**Issue by naviathan** [markwal/OctoPrint-PolarCloud#34]
When selecting Printers the icon view of the camera shot does not reflect the camera flip settings. Once selected the view is properly rotated (this requires gstreamer for some reason), but the viewer is in the center of the screen.
![polarcloudplugin001](https://user-images.githubusercontent.com/30502697/34536133-3e146b30-f092-11e7-8b6a-e2348f73f902.png)
![polarcloudplugin002](https://user-images.githubusercontent.com/30502697/34536134-3e2d1f36-f092-11e7-8af1-393ecec3bd04.png)

**Comment by dnewman-polar3d** [comment]
Thanks for the report!  I've pointed our web frontend engineer at this and hopefully we'll correct this shortly (as in next week; he's out sick at the moment).

**Comment by naviathan** [comment]
Awesome, thanks for the quick response!

**Comment by dnewman-polar3d** [comment]
When you have a chance, see if this issue is now resolved at [https://polar3d.com](https://polar3d.com).

**Comment by naviathan** [comment]
Perfect! Thank you for the quick response. Can't even get that kind of service from products I pay hundreds of dollars for.

**Comment by dnewman-polar3d** [comment]
Thanks for the followup and kind words.  It is appreciated.  I'll go ahead and close this issue out.  Feel free to re-open should you find it's not working after all.
