### ISSUE TITLE
Camera stream won't show on different network.

### ISSUE THREAD

**Issue by CodeBeau** [markwal/OctoPrint-PolarCloud#36]
I have Octoprint installed on an Ubuntu machine with the Polar Cloud plugin installed. The camera stream uses an absolute URL. I can get a stream from Polar Cloud on the same network as the printer, but if I connect to an outside network with the Internet, I can't get a stream. I can however control the printer.

Camera is a Logitech C270.

**Comment by dnewman-polar3d** [comment]
Correct.  You do not get the live camera stream if you are not on the same local network.   Instead, you just see still camera snapshots which are uploaded infrequently when the printer is idle (not printing) and about once every 20 seconds whilst printing.
