### ISSUE TITLE
No video stream

### ISSUE THREAD

**Issue by howsTricks** [markwal/OctoPrint-PolarCloud#4]
Video stream area (I'm assuming that's what it is) on the Polar Cloud interface shows a grey box with the broken image icon in it in the upper left. I also see a red camera icon on the upper right. I've installed all of the required packages through apt-get and restarted my pi but not getting any video. Confirmed I can see video on my local octoprint interface.

**Comment by markwal** [comment]
The plugin has to modify your webcam stream url so that it can show up in another webpage.  The default for octopi is (in OctoPrint->Settings->Webcam/Timelapse->Stream URL

/webcam/?action=stream

The plugin attempts to translate this to:

http://<ipaddress>/webcam/?action=stream

But can have trouble figuring out what the ipaddress is especially if you've got more than one network interface (wifi and ethernet, for example)

You can help it out by giving a full url in that box that works on your network.  For example,

http://<ipaddress>/webcam/?action=stream

Outside of your network, PolarCloud will just show snapshots that are updated every once in a while.

**Comment by dnewman-polar3d** [comment]
My guess is that the plugin is tell the cloud to use "/webcam/?action=stream" as the URL for the camera.  That is then fed to the SPA running in your webbrowser but it likely won't work -- it most certainly needs to be an absolute URL.  (However, I could make the backend detect that it's not absolute and glue your local IP to the front....)

**Comment by howsTricks** [comment]
Tried changing the Stream URL to `http:///webcam/?action=stream` but get the following in OctoPrint (note the broken image icon)
![image](https://user-images.githubusercontent.com/3517629/27518699-0e80a8c2-59e6-11e7-8c2e-1875a6a33105.png)

**Comment by howsTricks** [comment]
I get the same thing as before in the PolarCloud interface:

![image](https://user-images.githubusercontent.com/3517629/27518712-5773260e-59e6-11e7-80dc-693d8d95ec24.png)

**Comment by dnewman-polar3d** [comment]
Mark, let me know if there's anything I might do in the web server backend.  While I can pre-pend "http://<local-ip>" to relative URLs, that presumes the service is on port 80.  However, it's no big deal to do that....  I could deploy that this evening in production (and sooner on test beds).

**Comment by dnewman-polar3d** [comment]
Indeed, I definitely have to refresh the production systems tonight anyway.  Just discovered a typo in an html page which is causing filament diameter to not appear as one of the slicer config settings.... Ooops!  (Fortunately, it's the sort of frontend issue I'm qualified to diagnose and fix!  It came about as a result of some changes to support XYZ printers.)

**Comment by markwal** [comment]
@howsTricks That url has to actually have your octopi's ip address in it:

http://192.168.1.47/webcam/?action=stream

And it has to work with the Test button also.

Don't use 192.168.1.47  use the number (or name) from your address bar.

**Comment by howsTricks** [comment]
Ah, that makes more sense... Updated the URL to my OctoPrint IP, test shows the webcam (good) but the PolarCloud interface still shows the broken image icon.

**Comment by markwal** [comment]
You *might* have to restart octoprint after updating that URL for my plugin to register the new url with Polar Cloud.  And then you'll need to refresh the polar cloud page (give it a minute after restarting OctoPrint).

**Comment by dnewman-polar3d** [comment]
Agreed: you need to restart octoprint.  Either that or kill your network connection and restart it.  When reconnecting to the cloud, the revised URL is sent.  And then things are happy.

![screen shot 2017-06-25 at 1 03 35 pm](https://user-images.githubusercontent.com/20478854/27519356-c16f0306-59a6-11e7-9034-b511cdd58ec1.png)

But there's room for improvement... Don't want to have to change that setting in Octoprint each time your printer slurps a new and different IP via DHCP.

**Comment by howsTricks** [comment]
There we go! Thanks!

![image](https://user-images.githubusercontent.com/3517629/27519435-242f3932-59f4-11e7-8cbf-b82602d49456.png)

**Comment by markwal** [comment]
I believe with b2e1caf1, I'm now normalizing the url for the stream (might still guess the IP address wrong though...)

**Comment by 3dfernando** [comment]
I still can't get any stream, even though I use the full local URL: http://10.0.0.226/webcam/?action=stream
