### ISSUE TITLE
Use config file for MFG string

### ISSUE THREAD

**Issue by wjsteele** [markwal/OctoPrint-PolarCloud#42]
I'd like to switch to a configuration file to define the machine manufacturer type to allow certain manufacturers to use a configuration string as their manufacture type instead of using the default "op" string.  For example, Robo3D uses Octoprint in their printers, but show up as generic OP machines... if we could identify the machine (I.E., using a MFG.CONF file), we can automatically set up a configuration for their machines instead of using a default generic "Cartesian" machine profile.  We already use this string for specific manufactures currently, but will begin supporting "custom" manufacturer strings going forward.

**Comment by tinder-danielnewman** [comment]
That would be nice.
