### ISSUE TITLE
Make gcode files from Octoprint available for print from PolarCloud

### ISSUE THREAD

**Issue by yordanov-alexandar** [markwal/OctoPrint-PolarCloud#49]
I would like to be able to reprint some of my existing Gcode files that reside on the Octoprint machine while on the go

**Comment by markwal** [comment]
Well.... you sorta can, you can download them from the OctoPrint UI and then upload them into PolarCloud via the "G-Code Job" button.  When you click on a printer in the Polar UI, there is a "G-Code Job" button in the upper left hand corner.

But I'm guessing, what you'd like is for Polar to show you a list of available gcode from the OctoPrint box and let you start one of those.  We'd need to ask the Polar guys for that feature though.

**Comment by vmorrisPolar** [comment]
Hi @yordanov-alexandar, this is Van from Polar. We'll think about this and do some digging to see what work would be involved, we'll report back here if we work it into the development schedule.
