### ISSUE TITLE
Versioning issues (1.11)

### ISSUE THREAD

**Issue by Java-SE-Binary** [markwal/OctoPrint-PolarCloud#53]
I'm not sure if this is simply a problem with my install, or if it's a problem with the versioning of the current version (1.11). After updating the plugin, OctoPrint still thinks that the plugin is on 1.10, despite the supported Python version showing as >= 2.7, >4, telling me it _did_ actually update.

**Comment by markwal** [comment]
Shoot.  Had an uncommitted change when I pushed.  I thought I checked that.  :-(
