### ISSUE TITLE
Machine Type / Printer Make dropdowns are empty

### ISSUE THREAD

**Issue by vmorrisPolar** [markwal/OctoPrint-PolarCloud#63]
![image](https://user-images.githubusercontent.com/24441001/144119390-94db6b1f-7e7b-45a6-9905-814075756619.png)

User reported issue. OctoPrint and OctoPi fresh install less than two weeks ago. Logs coming soon.

**Comment by Buttrcup** [comment]
Anyone find any fixes to this?

**Comment by vmorrisPolar** [comment]
@Buttrcup the only one who reported it never circled back to give logs, seemed like theirs sorted out. I can try and help you out though. Can you post for the polar cloud plugin?
